### Missionary and Cannibals Code

We test out individual functions separately first. It is easier to do it this way. 

We pick this representation:

    [MMMCCC]
  
where the missionaries and cannibals are represented by column positions. A 1 or 0 denotes the river bank side.

The boat location is represented by a separate variable

In [1]:
import numpy as np
board=np.array([1,1,1,0,1,0]) #MMMCCC
goal=np.array([0,0,0,0,0,0])
BOAT=0

What is a valid move?

    000 111 - valid
    000 000 - valid
    001 001 - valid
    000 001 - valid more missionaries is ok
    111 110 - valid
    001 110 - not valid
    001 111 - not valid
    
To check we count the '1' on the first 3 column and compare with last 3 column. Same with '0'

In [2]:
#easier to test if test after the move is made. Can this simplified?
def isValidBoard(test):
    val1=False
    
    #we can't just count zero or one because they are coded by position
    m, mcounts = np.unique(test[:3], return_counts=True) #count how many 0 and 1
    c, ccounts = np.unique(test[3:], return_counts=True) #count how many 0 and 1
    
    mm=dict(zip(m, mcounts)) # make it into dictionary pairs
    cc=dict(zip(c, ccounts)) # make it into dictionary pairs

    if(mm.get(1) and cc.get(1)):
        if(mm.get(1)>=cc.get(1)): #valid if number of M >= C on Bank=1
            val1=True
        else:
            return False
    if(mm.get(0) and cc.get(0)):
        if(mm.get(0)>=cc.get(0)): #valid if number of M >= C on Bank=0
            val1=True
        else:
            return False
    if(mm.get(0) and cc.get(1)):
        if(mm.get(0)==3):
            return True
    if(mm.get(1) and cc.get(0)):
        if(mm.get(1)==3):
            return True
    return val1 

In [3]:
test=[0,0,0, 0,0,1] #valid
print(isValidBoard(test))
test=[1,1,1, 1,1,0] # valid
print(isValidBoard(test))
test=[0,0,1, 1,1,0] # not valid
print(isValidBoard(test))
test=[0,0,1, 1,1,1] # not valid
print(isValidBoard(test))
test=[1, 0, 0, 0, 0, 0] # not valid
print(isValidBoard(test))
test=[1, 1, 1, 0, 0, 0] #valid
print(isValidBoard(test))
test=[0, 0, 0, 1, 1, 1] #valid
print(isValidBoard(test))

True
True
False
False
False
True
True


In [4]:
def isValidMove(board, move):
    val1=False
    
    test=[b for b in board]
    
    #move must from same side
    if(move[0]==move[1]):
        if(move[0]>=0):
            test[move[0]]=int(not test[move[0]])
        if(move[1]>=0):
            test[move[1]]=int(not test[move[1]])
    #print(test)
    #we can't just count zero or one because they are coded by position
    m, mcounts = np.unique(test[:3], return_counts=True) #count how many 0 and 1
    c, ccounts = np.unique(test[3:], return_counts=True) #count how many 0 and 1

    mm=dict(zip(m, mcounts)) # make it into dictionary pairs
    cc=dict(zip(c, ccounts)) # make it into dictionary pairs

    if(mm.get(1) and cc.get(1)):
        if(mm.get(1)>=cc.get(1)): #valid if number of M >= C on Bank=1
            val1=True
        else:
            return False
    if(mm.get(0) and cc.get(0)):
        if(mm.get(0)>=cc.get(0)): #valid if number of M >= C on Bank=0
            val1=True
        else:
            return False
    if(mm.get(0) and cc.get(1)):
        if(mm.get(0)==3):
            return True
    if(mm.get(1) and cc.get(0)):
        if(mm.get(1)==3):
            return True
    return val1 

First attemp to get all the moves, first we try to get one move.
Conditions we must handle 
    
    BOAT==0 

    111110 - Must pick the '0'
    000001 - Randomly pick 2 '0'
    111100 - Pick 2 '0'
    000011 - Pick 2 '0'



In [5]:
def getMoves(board, BOAT, lastMove=None):
    a,b=-1,-1
    moves=[]
    zero=np.where(board==0)[0]
    one=np.where(board==1)[0]

    if(BOAT==0):
        if(len(zero)==1):  
            a=zero[0] #only 1 choice
            moves=[[a,b]]
        elif(len(zero)==2):  
            a=zero[0] #only 1 choice
            b=zero[1] #only 1 choice
            moves=[[a,b]]
        else:#select all combinations not randomly
            for i in itertools.combinations(zero,2):
                moves.append([i[0],i[1]])

    elif(BOAT==1):
        if(len(one)==1):  
            a=one[0] #only 1 choice
            moves=[[a,b]]
        elif(len(one)==2):  
            a=one[0] #only 1 choice
            b=one[1] #only 1 choice
            moves=[[a,b]]
        else:
            for i in itertools.combinations(one,2):
                moves.append([i[0],i[1]])
    
    return moves

Let's test them

In [7]:
import itertools
BOAT=0
board=np.array([1,1,1,0,1,0]) #MMMCCC
m=getMoves(board,BOAT)
print(m)
board=np.array([1,1,1,0,1,1]) #MMMCCC
m=getMoves(board,BOAT)
print(m)
board=np.array([0,0,0,0,1,0]) #MMMCCC
m=getMoves(board,BOAT)
print(m)

[[3, 5]]
[[3, -1]]
[[0, 1], [0, 2], [0, 3], [0, 5], [1, 2], [1, 3], [1, 5], [2, 3], [2, 5], [3, 5]]


In [8]:
BOAT=1
board=np.array([1,1,1,0,1,0]) #MMMCCC
m=getMoves(board,BOAT)
print(m)
board=np.array([1,1,1,0,1,1]) #MMMCCC
m=getMoves(board,BOAT)
print(m)
board=np.array([0,0,0,0,1,0]) #MMMCCC
m=getMoves(board,BOAT)
print(m)

[[0, 1], [0, 2], [0, 4], [1, 2], [1, 4], [2, 4]]
[[0, 1], [0, 2], [0, 4], [0, 5], [1, 2], [1, 4], [1, 5], [2, 4], [2, 5], [4, 5]]
[[4, -1]]


In [9]:
BOAT=1
board=np.array([1,1,1,1,1,0]) #MMMCCC
m=getMoves(board,BOAT)
for i in m:
    print(i)
    print(isValidMove(board,i))
    print()

[0, 1]
True

[0, 2]
True

[0, 3]
True

[0, 4]
True

[1, 2]
True

[1, 3]
True

[1, 4]
True

[2, 3]
True

[2, 4]
True

[3, 4]
True



In [10]:
def makeMove(board,move):
    test=[b for b in board] # can't do this test=board
    if(move[0]>=0):
        test[move[0]]=int(not test[move[0]])
    if(move[1]>=0):
        test[move[1]]=int(not test[move[1]])
    #print(test)    
    return test

Edit getMoves so that it only returns valid moves

In [11]:
def getMoves(board, BOAT):
    a,b=-1,-1
    moves=[]
    zero=np.where(board==0)[0]
    one=np.where(board==1)[0]

    if(BOAT==0):
        if(len(zero)==1):  
            a=zero[0] #only 1 choice
            moves=[[a,b]]
        elif(len(zero)==2):  
            a=zero[0] #only 1 choice
            b=zero[1] #only 1 choice
            moves=[[a,b]]
        else:#select all combinations not randomly
            for i in itertools.combinations(zero,2):
                moves.append([i[0],i[1]])

    elif(BOAT==1):
        if(len(one)==1):  
            a=one[0] #only 1 choice
            moves=[[a,b]]
        elif(len(one)==2):  
            a=one[0] #only 1 choice
            b=one[1] #only 1 choice
            moves=[[a,b]]
        else:
            for i in itertools.combinations(one,2):
                moves.append([i[0],i[1]])

    validmoves=[m for m in moves if isValidMove(board,m)==True]
    #validmoves=moves
    return validmoves

In [12]:
BOAT=1
board=np.array([1,1,1,1,0,0]) #MMMCCC
m=getMoves(board,BOAT)
for i in m:
    print(i)
    print(board)
    print(isValidMove(board,i))
    print()

[0, 1]
[1 1 1 1 0 0]
True

[0, 2]
[1 1 1 1 0 0]
True

[0, 3]
[1 1 1 1 0 0]
True

[1, 2]
[1 1 1 1 0 0]
True

[1, 3]
[1 1 1 1 0 0]
True

[2, 3]
[1 1 1 1 0 0]
True

